# Generated by Django 4.2.10 on 2024-08-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_balance_balance_balance_client_subscription_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='balance',
            field=models.PositiveIntegerField(blank=True, default=1000, null=True, verbose_name='Баланс'),
        ),
    ]
